services:
  cloudflare-dns-manager:
    build: .
    container_name: cloudflare-dns-manager
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_NAME=nugz92.net
      - CONFIG_PATH=/app/config.json
      - LOG_PATH=/app/logs/dns_manager.log
    volumes:
      - ./config.json:/app/config.json:ro
      - ./logs:/app/logs
    restart: unless-stopped
